from pathlib import Path
import json,shutil,re,html,fitz
from PIL import Image
root=Path(__file__).parent; out=root.parent; assets=out/'assets';assets.mkdir(exist_ok=True)
source=root/'upload'
files=json.loads((root/'asset-map.json').read_text()) if (root/'asset-map.json').exists() else {}
for p in (source.iterdir() if source.exists() else []):
 if p.name.startswith(('Screenshot from 2026-09-25','Screenshot from 2026-09-28')): continue # Layout reference images are not site content.
 if p.suffix.lower() not in ['.pdf','.png','.jpeg','.jpg']: continue
 slug=re.sub(r'[^a-z0-9]+','-',p.stem.lower()).strip('-')
 name=slug+p.suffix.lower();shutil.copy2(p,assets/name);files[p.name]='/assets/'+name
 if p.suffix.lower()=='.pdf':
  doc=fitz.open(p);doc[0].get_pixmap(matrix=fitz.Matrix(1.25,1.25)).save(str(assets/(slug+'-preview.jpg')))
 else:
  im=Image.open(p).convert('RGB');im.thumbnail((1600,1600));im.save(assets/(slug+'-web.jpg'),quality=87,optimize=True)
(root/'asset-map.json').write_text(json.dumps(files,indent=2))
def asset(name):return files[name]
def thumb(name):
 s=Path(files[name]);return str(s.with_name(s.stem+('-preview.jpg' if s.suffix=='.pdf' else '-web.jpg')))
def esc(s):return html.escape(str(s),quote=True)
arrow='<span aria-hidden="true">↗</span>'
links={'LinkedIn':'https://www.linkedin.com/in/md-basim-al-zabir-shammo-759082205/','Google Scholar':'https://scholar.google.com/citations?user=FGLF-0sAAAAJ&hl=en','ORCID':'https://orcid.org/0009-0006-0693-923X','Email':'mailto:al.zabir.shammo@gmail.com'}
nav=['Home','Education','Projects','Research','Publications','Courses','Skills','Experience','Achievements']
search=[]
def ext(url,label,cls='text-link'):return f'<a class="{cls}" href="{esc(url)}" target="_blank" rel="noopener">{esc(label)} {arrow}</a>'
def doclink(name,label='View certificate'):return ext(asset(name),label)
def gallery(names,captions=None):
 captions=captions or [Path(n).stem.replace('_',' ') for n in names]
 return '<div class="gallery">'+''.join(f'<figure><a href="{asset(n)}" target="_blank" rel="noopener"><img src="{thumb(n)}" alt="{esc(c)}" loading="lazy"></a><figcaption>{esc(c)}</figcaption></figure>' for n,c in zip(names,captions))+'</div>'
def heading(kicker,title,desc=''):return f'<header class="page-heading"><p class="eyebrow">{kicker}</p><h1>{title}</h1>'+ (f'<p class="intro">{desc}</p>' if desc else '')+'</header>'
def page(path,title,body,section=None):
 section=section or title; active=section.split('/')[0]; dest=out/path.strip('/')/'index.html' if path!='/' else out/'index.html';dest.parent.mkdir(parents=True,exist_ok=True)
 menu=''.join(f'<a href="{("/" if n=="Home" else "/"+n.lower()+"/")}"'+(' aria-current="page"' if n==active else '')+f'>{n}</a>' for n in nav)
 social=''.join(f'<a href="{esc(v)}"'+(' target="_blank" rel="noopener"' if not v.startswith('mailto') else '')+f' aria-label="{k}" title="{k}">{ {"LinkedIn":"in","Google Scholar":"<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><path d=\"m2 9 10-6 10 6-10 6zM6 12v6c4 3 8 3 12 0v-6\"/></svg>","ORCID":"iD","Email":"<svg viewBox=\"0 0 24 24\" aria-hidden=\"true\"><rect x=\"3\" y=\"5\" width=\"18\" height=\"14\" rx=\"1\"/><path d=\"m3 6 9 7 9-7\"/></svg>"}[k]}</a>' for k,v in links.items())
 text=re.sub('<[^>]+>',' ',body)
 search_url='/projects/#'+path.strip('/').split('/')[-1] if path.startswith('/projects/') and path!='/projects/' else path
 if path!='/projects/embedded-prototypes/': search.append({'title':title,'url':search_url,'text':html.unescape(re.sub(r'\s+',' ',text))})
 dest.write_text(f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(title)} — Md. Basim Al Zabir Shammo</title><meta name="description" content="Research portfolio of Md. Basim Al Zabir Shammo. Robotics, physics-informed machine learning, sensor fusion, publications, and projects."><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='12' fill='%231b3530'/%3E%3Ctext x='32' y='43' text-anchor='middle' font-family='Arial' font-size='34' fill='white'%3EB%3C/text%3E%3C/svg%3E"><link rel="stylesheet" href="/style.css"><script src="/app.js" defer></script></head><body><a class="skip" href="#main">Skip to content</a><header class="site-header"><a class="wordmark" href="/">Basim Al Zabir<span>Shammo</span></a><nav id="navigation" aria-label="Main navigation">{menu}</nav><div class="header-actions"><button id="search-open" class="icon-button" aria-label="Search this site"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg></button><button id="menu-toggle" class="icon-button" aria-label="Open menu" aria-expanded="false" aria-controls="navigation"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3 6h18M3 12h18M3 18h18"/></svg></button></div></header><main id="main" class="{'home' if path=='/' else 'interior'}">{body}</main><footer><div class="footer-inner"><div><p class="eyebrow">CONTACT</p><a class="email" href="mailto:al.zabir.shammo@gmail.com">al.zabir.shammo@gmail.com</a></div><div class="social">{social}</div><p class="copyright">© 2026 · Md. Basim Al Zabir Shammo</p></div></footer><dialog id="search-dialog" aria-labelledby="search-title"><div class="dialog-head"><h2 id="search-title">Search the portfolio</h2><button class="icon-button" id="search-close" aria-label="Close search">×</button></div><label class="sr-only" for="search-input">Search pages, papers, and projects</label><input id="search-input" type="search" placeholder="Search pages, papers, and projects…"><p id="search-status" role="status">Type a topic, skill, or publication title.</p><div id="search-results"></div></dialog></body></html>''')

home=f'''<div class="profile-layout">
<aside class="profile-sidebar" aria-label="Profile and contact links">
<img class="profile-photo" src="{thumb('photo_6179059420743011879_y.jpg')}" alt="Md. Basim Al Zabir Shammo" width="170" height="170" fetchpriority="high">
<p class="profile-name">Basim Al Zabir Shammo</p>
<p class="profile-affiliation">Pabna University of Science and Technology</p>
<a class="profile-email" href="{links['Email']}"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/></svg><span>al.zabir.shammo@gmail.com</span></a>
<div class="profile-links">
<a href="{esc(links['Google Scholar'])}" target="_blank" rel="noopener"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m2 9 10-6 10 6-10 6zM6 12v6c4 3 8 3 12 0v-6M22 9v8"/></svg><span>Google Scholar</span></a>
<a href="{links['ORCID']}" target="_blank" rel="noopener"><span class="profile-link-icon orcid-icon" aria-hidden="true">iD</span><span>ORCID</span></a>
<a href="{links['LinkedIn']}" target="_blank" rel="noopener"><span class="profile-link-icon linkedin-icon" aria-hidden="true">in</span><span>LinkedIn</span></a>
</div>
<a class="button profile-cv" href="{asset('Md.Basim_Al_Zabir_Shammo_CV.pdf')}" download><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/></svg>Download my CV</a>
</aside>
<div class="profile-content">
<header class="profile-heading"><h1>Md. Basim Al Zabir Shammo</h1><p>Information &amp; Communication Engineer <span aria-hidden="true">·</span> Robotics and Machine Learning Researcher</p></header>
<section class="profile-section" aria-labelledby="biography-title"><h2 id="biography-title"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="7" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2z"/></svg>Biography</h2>
<p>My background is in Information and Communication Engineering at Pabna University of Science and Technology. I work on robotics and machine learning, bringing together sensor data, hardware, and computer models. My research focuses on digital twins, sensor fusion, and robots that use cameras to understand their surroundings.</p>
<p>My projects include mobile robots, Arduino systems, and small hardware prototypes. I also study health monitoring with PPG signals and computer vision for satellite images and traffic analysis.</p></section>
<section class="profile-section" aria-labelledby="interests-title"><h2 id="interests-title"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/><path d="M12 1v3m0 16v3M1 12h3m16 0h3"/></svg>Research Interests</h2>
<div class="research-focus"><p class="focus-label">Areas of focus</p><ul class="interest-tags"><li>Physics-informed machine learning</li><li>Digital twins</li><li>Sensor fusion</li><li>Autonomous robotics</li><li>Computer vision</li><li>Biomedical signal processing</li></ul></div>
</section>
</div></div>'''
page('/','Home',home)
education = heading('ACADEMIC BACKGROUND', 'Education') + """<div class="education-list">
<section class="education-row"><img class="institution-logo" src="/assets/institutions/pust.png" alt="Pabna University of Science and Technology logo" width="120" height="130"><div><h2>Bachelor of Science in Information and Communication Engineering</h2><p class="education-date">2022–2026</p><p>Pabna University of Science and Technology, Pabna</p><p>CGPA: <strong>3.36</strong> (3.48 in the last 4 semesters)</p></div></section>
<section class="education-row"><img class="institution-logo" src="/assets/institutions/rajuk.png" alt="Rajuk Uttara Model College logo" width="120" height="130"><div><h2>Higher Secondary School Certificate</h2><p class="education-date">2018–2020</p><p>Rajuk Uttara Model College, Dhaka</p><p>GPA: <strong>5.00/5.00</strong></p><ul><li>Champion, Rajuk Intra Talent Hunt Science Project Competition 2018</li></ul></div></section>
<section class="education-row"><img class="institution-logo" src="/assets/institutions/rcpsc.png" alt="Rajendrapur Cantonment Public School and College logo" width="120" height="130"><div><h2>Secondary School Certificate</h2><p class="education-date">2006–2018</p><p>Rajendrapur Cantonment Public School and College, Gazipur</p><p>GPA: <strong>5.00/5.00</strong></p><ul><li>Ministry of Education Board Scholarship for SSC Exam (General)</li><li>Ministry of Education Board Scholarship for JSC Exam (Talentpool)</li><li>2nd Runner-up, International Mother Language Essay Writing Competition 2014</li></ul></div></section>
</div>"""
page('/education/', 'Education', education)

projects=[
 ('digital-twins', 'Physics-informed digital twins', 'Hardware-in-the-loop · Sensor fusion', 'Sensor Fusion.jpeg', 'Mathematical models and multi-modal telemetry for micro-mechatronic systems.', ['Sensor Fusion.jpeg'], ['Hardware setup for sensor fusion and embedded-system experiments.'], '<p>I modeled dynamic loads through electrical impedance to remove the need for physical encoders in edge-deployed digital twins.</p><ul><li>Developed a Thermal Health Index from multi-modal telemetry and GRU prediction residuals.</li><li>Forecast thermal saturation under changing loads.</li><li>Used Monte Carlo Dropout to quantify epistemic uncertainty.</li></ul><p>The associated manuscript, <em>The Limits of Physics-Informed Digital Twins Under Hardware-Constrained Sampling: An HIL Study for Micro-Mechatronics</em>, is in revision at the Journal of Intelligent Manufacturing.</p>'),
 ('vision-robotics', 'Vision-based mobile robotics', 'Computer vision · Coverage planning', 'VisionRobot.jpeg', 'Object segmentation and IR-vision fusion for autonomous coverage.', ['VisionRobot.jpeg'], ['Mobile robotic platform with sensors and embedded electronics.'], '<p>I integrated YOLOv11n-seg with zig-zag coverage planning and developed an IR-vision fusion algorithm to resolve deadlocks.</p><p>The approach achieved <strong>94.17% coverage in Webots simulation</strong>. This figure describes simulation performance, not a physical field trial.</p><p>The associated manuscript, <em>Vision-Based Crack Detection and Coverage Planning for Autonomous Mobile Robots</em>, is in revision at the International Journal of Intelligent Robotics and Applications.</p>'),
 ('humanoid', '17-DOF humanoid robot', 'Robotics · Hardware assembly', '17dof_Robot.jpeg', 'A closer look at the humanoid robot and its hardware.', ['17dof_Robot.jpeg', '17dof02.jpeg'], ['17-DOF humanoid robot in the laboratory.', 'Basim with the humanoid platform.'], '<p>A humanoid robotics platform with articulated joints, servo assemblies, and an exposed electronic control setup.</p>'),
 ('voice-radio-robot', 'Voice and Radio Controlled Robot', 'Arduino · HC-05 Bluetooth · Android app', 'photo_6172214870665794035_y.jpg', 'Built with Arduino and an HC-05 Bluetooth module.', ['photo_6172214870665794035_y.jpg'], ['Voice and radio controlled robot built with Arduino and an HC-05 Bluetooth module.'], '<ul><li>Built with Arduino and an HC-05 Bluetooth module.</li><li>Received voice commands over Bluetooth from a custom Android mobile app.</li></ul>'),
 ('arduino-obstacle-robot', 'First Arduino Obstacle-Avoiding Robot', 'Arduino · Sonar sensor', 'photo_6172214870665794033_y.jpg', 'Built our first obstacle-detecting robot using Arduino and a sonar sensor.', ['photo_6172214870665794033_y.jpg'], ['First Arduino robot with a sonar sensor, programmed to stop when an obstacle is detected.'], '<ul><li>Built our first obstacle-detecting robot using Arduino and a sonar sensor.</li><li>The robot stopped when the sensor detected an object in front of it.</li></ul>'),
 ('mini-obstacle-robot', 'Mini Obstacle-Avoiding Robot', 'Custom JRC board · Sonar sensor', 'Screenshot from 2026-05-12 13-46-46.png', 'Built a mini robot using a custom JRC board and a sonar sensor.', ['Screenshot from 2026-05-12 13-46-46.png'], ['Mini obstacle-avoiding robot with a custom JRC board and sonar sensor.'], '<ul><li>Built a mini robot using a custom JRC board and a sonar sensor.</li><li>The robot detected and moved around objects in front of it.</li></ul>'),
 ('knock-door-lock', 'Knock-Pattern Door Unlocking Mechanism', 'Arduino · Knock sensing · Door lock', 'Screenshot from 2026-05-12 13-47-33.png', 'Used a buzzer as a sensor to detect a specific knock pattern.', ['Screenshot from 2026-05-12 13-47-33.png'], ['Arduino door-unlocking prototype using a buzzer to sense a knock pattern.'], '<ul><li>Used a buzzer as a sensor to detect a specific knock pattern.</li><li>The door unlocked when the detected knocks matched the preset pattern.</li></ul>'),
]
project_descriptions={'digital-twins': ['I built a digital model of a small motor system.', 'The model uses sensor readings from the real hardware.', 'It tracks changes in load and heat during use.', 'This helps study the system and predict how hot it may become.'], 'vision-robotics': ['I worked on a mobile robot that uses a camera to find cracks.', 'The robot follows a zig-zag path to cover the area.', 'Camera data and infrared sensors help it avoid getting stuck.', 'It covered 94.17% of the test area in a Webots simulation.'], 'humanoid': ['I worked with a humanoid robot with 17 degrees of freedom.', 'Its joints use servo motors to move.', 'The frame holds the motors, wires, and control parts.', 'This work involved the robot’s hardware and joint setup.'], 'voice-radio-robot': ['We built this robot using Arduino and an HC-05 Bluetooth module.', 'We also made an Android app to send voice commands.', 'The app sent these commands to the robot over Bluetooth.', 'The robot moved in response to those commands.'], 'arduino-obstacle-robot': ['This was our first robot built with Arduino and a sonar sensor.', 'The sensor checked for objects in front of the robot.', 'When it found an object, the robot stopped.', 'The project focused on sensing obstacles and controlling movement.'], 'mini-obstacle-robot': ['We built this mini robot with a custom JRC board.', 'It used a sonar sensor to check the path ahead.', 'When it found an object, it changed its path.', 'This allowed the robot to move around obstacles.'], 'knock-door-lock': ['We built a door lock that responds to a set knock pattern.', 'A buzzer worked as the sensor and picked up the knocks.', 'The Arduino checked the pattern against the stored one.', 'When the pattern matched, the door unlocked.'], 'rfid-access': ['We built a door access system using an RFID reader and an ESP8266 board.', 'It checked the tag before allowing entry.', 'A servo controlled the lock, and a buzzer gave a sound signal.', 'The system saved the tag ID and access result in a local database.']}
research_descriptions={'digital-twins': ['This study looks at how a digital model can track a small motor system.', 'It combines a maths-based model with readings from several sensors.', 'The data helps track the system and predict changes in heat.', 'We also studied how certain the model’s predictions were.'], 'vision-robotics': ['This study combines crack detection with route planning for a mobile robot.', 'A camera model finds cracks while the robot follows a zig-zag path.', 'Infrared and camera readings help the robot avoid getting stuck.', 'The method reached 94.17% coverage in a Webots simulation.'], 'damage-assessment': ['We used satellite images to study building damage after Hurricane Harvey.', 'A model called ViT-B/32 reached 97.85% accuracy in our tests.', 'It performed better than the CNN model used for comparison.', 'Heatmaps showed which parts of each image influenced the result.'], 'hepatitis-c': ['We compared ten machine learning models for detecting Hepatitis C.', 'The models used clinical data to make their predictions.', 'AdaBoost gave the highest accuracy among the models we tested.', 'The study explored how these tools could support automated detection.'], 'mobile-ppg': ['This study used a phone camera to record changes in blood flow.', 'We processed these PPG signals with machine learning models.', 'The models estimated blood pressure, blood oxygen, stress, and heart health risks.', 'The aim was to study health monitoring with a mobile device.'], 'nightmare-prediction': ['We studied how machine learning could help predict nightmares in children.', 'The work brought data analysis into child mental health research.', 'It focused on using data to support psychological assessment.', 'The study was presented at COMPAS 2025.'], 'ppg-stress': ['We studied how PPG signals could help detect stress.', 'Machine learning models looked for patterns in these signals.', 'The aim was to assess stress using data from the body.', 'The research was presented at QPAIN 2025.'], 'vehicle-detection': ['We used YOLOv8 to find and classify vehicles in traffic footage.', 'The study focused on roads in Bangladesh.', 'It explored how real-time video could support traffic monitoring.', 'We presented the work at ICRPSET 2024 in Rajshahi.']}
def description_paragraph(lines):
 return '<p class="entry-description">'+'<br>'.join(esc(line) for line in lines)+'</p>'
def expandable_entry(slug,title,image_url,image_full,image_alt,lines,status='',research=False,extra_names=None,extra_captions=None):
 row_class='project-row research-row' if research else 'project-row'
 extras=''
 for name,caption in zip(extra_names or [],extra_captions or []):
  extras+=f'<figure><a class="project-visual" href="{asset(name)}" target="_blank" rel="noopener" aria-label="Open image: {esc(caption)}"><img src="{thumb(name)}" alt="{esc(caption)}" width="240" height="240" loading="lazy"></a><figcaption>{esc(caption)}</figcaption></figure>'
 extra_html='<div class="entry-extra-media">'+extras+'</div>' if extras else ''
 status_html=f'<p class="research-status">{esc(status)}</p>' if status else ''
 chevron='<svg class="entry-chevron" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="m6 9 6 6 6-6"/></svg>'
 return f'<article class="{row_class}" id="{slug}"><a class="project-visual" href="{image_full}" target="_blank" rel="noopener" aria-label="Open image: {esc(title)}"><img src="{image_url}" alt="{esc(image_alt)}" width="240" height="240" loading="lazy"></a><details class="entry-details"><summary><h2><span>{esc(title)}</span>{chevron}</h2></summary><div class="entry-body">{description_paragraph(lines)}{status_html}{extra_html}</div></details></article>'
project_rows={}
for slug,title,meta,img,desc,names,captions,detail in projects:
 lines=project_descriptions[slug]
 project_rows[slug]=expandable_entry(slug,title,thumb(img),asset(img),captions[0],lines,extra_names=names[1:],extra_captions=captions[1:])
 page('/projects/'+slug+'/',title,f'<a class="back-link" href="/projects/">← All projects</a>'+heading(meta,title)+f'<div class="detail-copy">{description_paragraph(lines)}</div>'+gallery(names,captions),'Projects')
prototype_slugs=['voice-radio-robot','arduino-obstacle-robot','mini-obstacle-robot','knock-door-lock']
page('/projects/embedded-prototypes/','Arduino & Custom-Board Projects','<a class="back-link" href="/projects/">← All projects</a>'+heading('ROBOTS & EMBEDDED SYSTEMS','Arduino & Custom-Board Projects')+'<div class="project-list">'+''.join(project_rows[slug] for slug in prototype_slugs)+'</div>','Projects')
pubs=[
('2026','Journal','Vision Transformer-based Damage Assessment from Post-Disaster Satellite Imagery: An Applied Study on Hurricane Harvey','Jakaria Habib, Md. Imran Hossain, Md. Basim Al Zabir Shammo, et al.','Earth Science Informatics · Springer Nature','https://doi.org/10.1007/s12145-026-02142-6',None,None),
('2026','Conference','Real-Time RFID Authentication and Access Control System with Networked Logging','Lamia Islam, Md. Basim Al Zabir Shammo, et al.','QPAIN 2026 · IEEE','https://ieeexplore.ieee.org/document/11546467',None,'Screenshot from 2026-09-24 15-21-07.png'),
('2025','Conference','Machine Learning-Based Hepatitis C Detection Using Ensemble Boosting','Md. Basim Al Zabir Shammo, Lamia Islam, et al.','BIM 2025 · Lecture Notes in Networks and Systems · Springer Nature','https://link.springer.com/chapter/10.1007/978-3-032-15764-5_50','461.pdf',None),
('2025','Conference','Machine Learning-Based Prediction of Nightmares in Children: A Pediatric Psychological Integration','Lamia Islam, Md. Basim Al Zabir Shammo, et al.','COMPAS 2025 · IEEE','https://ieeexplore.ieee.org/document/11381639','COMPAS-2025.pdf',None),
('2025','Conference','A Machine Learning Framework for Stress Detection Using Photoplethysmography (PPG) Signals','Md. Rashed, Md. Basim Al Zabir Shammo, et al.','QPAIN 2025 · IEEE','https://ieeexplore.ieee.org/document/11171913','PID-1435.pdf',None),
('2025','Conference','Remote Health Monitoring via PPG Signal Processing and Machine Learning Using Mobile Devices','Md. Akash Miya, …, Md. Basim Al Zabir Shammo, et al.','ICCIT 2025 · IEEE','https://ieeexplore.ieee.org/document/11491546',None,'Screenshot from 2026-09-24 15-20-32.png'),
('2024','Conference','Vehicle Classification and Detection Using YOLOv8: A Study on Highway Traffic Analysis','Naima Islam, …, Md. Basim Al Zabir Shammo','ICRPSET 2024 · IEEE','https://ieeexplore.ieee.org/document/10955913',None,'Screenshot from 2026-09-24 15-20-08.png')]
research_projects=[
 ('damage-assessment','Vision Transformer-Based Damage Assessment','Computer vision · Deep learning · Remote sensing',0,['Applied a pre-trained ViT-B/32 to post-disaster satellite imagery, achieving 97.85% accuracy and outperforming the CNN baseline.','Used attention heatmaps to help interpret structural damage.']),
 ('hepatitis-c','Machine Learning-Based Hepatitis C Detection','Healthcare analytics · Ensemble learning',2,['Compared ten machine learning models for Hepatitis C detection.','AdaBoost achieved the highest accuracy among the evaluated models.']),
 ('mobile-ppg','Smartphone-Based Physiological Monitoring','Biomedical signal processing · Machine learning',5,['Processed PPG signals captured through a smartphone camera.','Applied SVM and regression models to estimate blood pressure, SpO₂, stress, and cardiovascular risk indicators.']),
 ('nightmare-prediction','Machine Learning-Based Prediction of Nightmares in Children','Machine learning · Pediatric mental health',3,['Studied machine learning approaches to childhood nightmare prediction.','Connected data analysis with pediatric psychological assessment.']),
 ('ppg-stress','Stress Detection Using PPG Signals','Biomedical signal processing · Machine learning',4,['Developed a machine learning framework for stress detection from photoplethysmography (PPG) signals.']),
 ('vehicle-detection','YOLOv8-Based Vehicle Detection and Classification','Computer vision · Traffic analysis',6,['Applied YOLOv8 to identify and classify vehicles in real-time traffic footage from Bangladesh.','Presented at ICRPSET 2024 in Rajshahi, Bangladesh.'])
]
research_rows=[]
for slug,title,img,status in [
 ('digital-twins','Physics-Informed Digital Twins for Micro-Mechatronic Systems','Sensor Fusion.jpeg','Manuscript in revision · Journal of Intelligent Manufacturing'),
 ('vision-robotics','Vision-Based Crack Detection and Coverage Planning','VisionRobot.jpeg','Manuscript in revision · International Journal of Intelligent Robotics and Applications')
]:
 lines=research_descriptions[slug]
 research_rows.append(expandable_entry(slug,title,thumb(img),asset(img),'Hardware platform for '+title,lines,status,research=True))
 search.append({'title':title,'url':'/research/#'+slug,'text':' '.join(lines)})
for slug,title,meta,pub_index,points in research_projects:
 image_url=thumb('Statellite imagery Research.png') if slug=='damage-assessment' else '/assets/projects/'+slug+'.svg'
 full_image=asset('Statellite imagery Research.png') if slug=='damage-assessment' else image_url
 image_alt='Vision Transformer architecture for satellite imagery research' if slug=='damage-assessment' else 'Method overview for '+title
 year,kind=pubs[pub_index][:2]
 lines=research_descriptions[slug]
 research_rows.append(expandable_entry(slug,title,image_url,full_image,image_alt,lines,f'{year} · {kind} publication',research=True))
 search.append({'title':title,'url':'/research/#'+slug,'text':' '.join(lines)})
page('/research/','Research',heading('STUDIES & PUBLICATIONS','Research')+'<div class="project-list research-projects">'+''.join(research_rows)+'</div>')

rfid_title='Real-Time RFID Authentication and Access Control'
rfid_meta='Embedded systems · RFID · Networked logging'
rfid_lines=project_descriptions['rfid-access']
project_rows['rfid-access']=expandable_entry('rfid-access',rfid_title,thumb('RFID.jpg'),asset('RFID.jpg'),'RFID access-control hardware prototype with reader, breadboard, servo lock, and batteries',rfid_lines,extra_names=['RFID2.jpg'],extra_captions=['System diagram: RFID authentication, lock control, and networked logging.'])
page('/projects/rfid-access/',rfid_title,'<a class="back-link" href="/projects/">← All projects</a>'+heading(rfid_meta,rfid_title)+f'<div class="detail-copy">{description_paragraph(rfid_lines)}</div>'+gallery(['RFID.jpg','RFID2.jpg'],['RFID access-control hardware prototype.','System diagram: RFID authentication, lock control, and networked logging.']),'Projects')
project_order=['digital-twins','vision-robotics','humanoid','voice-radio-robot','arduino-obstacle-robot','mini-obstacle-robot','knock-door-lock','rfid-access']
page('/projects/','Projects',heading('ROBOTICS & HARDWARE','Projects')+'<div class="project-list">'+''.join(project_rows[slug] for slug in project_order)+'</div>')
def pubnav(which):return '<nav class="subnav" aria-label="Publication categories">'+''.join(f'<a href="{url}"'+(' aria-current="page"' if label==which else '')+f'>{label}</a>' for label,url in [('Published','/publications/'),('Under review','/publications/under-review/'),('Presentations','/publications/presentations/')])+'</nav>'
paper_descriptions={
 'https://doi.org/10.1007/s12145-026-02142-6': 'Rapid damage evaluation supports post-disaster response. Our study demonstrates that a pre-trained Vision Transformer (ViT-B32) outperforms a standard CNN baseline, achieving 97.85% accuracy. Through self-attention mechanisms, the ViT model captures global spatial relationships to identify subtle damage in visually cluttered disaster zones. We generated attention heatmaps to pinpoint structural damage, providing an interpretable and actionable tool for disaster management workflows.',
 'https://link.springer.com/chapter/10.1007/978-3-032-15764-5_50': 'Our research evaluated ten machine learning models to help develop an automated diagnostic system for Hepatitis C. We demonstrated that ensemble-boosting algorithms deliver better performance, with our AdaBoost classifier achieving the best accuracy.',
 'https://ieeexplore.ieee.org/document/11491546': 'This research presents a noninvasive, smartphone-based physiological monitoring system. By processing photoplethysmographic (PPG) signals captured via a mobile camera and applying machine learning models, including SVMs and multivariate regression, our system estimates indicators such as blood pressure, SpO₂, stress levels, and cardiovascular risk.',
 'https://ieeexplore.ieee.org/document/11381639': 'This work highlights the potential of data science to improve pediatric care and provide clinicians with data-driven tools for mental health assessment. I would like to thank my co-authors for their dedication and collaborative efforts on this project.',
 'https://ieeexplore.ieee.org/document/10955913': 'This work was presented at the 2024 International Conference on Recent Progresses in Science, Engineering and Technology (ICRPSET), held in Rajshahi, Bangladesh. Our study focuses on developing a vehicle identification framework using the YOLOv8 model tailored for the roadways of Bangladesh. Using real-time traffic footage, we aimed to improve traffic flow, reduce congestion, and support smart city initiatives.'
}
def pubrow(p):
 year,kind,title,authors,venue,url,cert,screen=p
 index=pubs.index(p)
 slug=['damage-assessment','rfid-access','hepatitis-c','nightmare-prediction','ppg-stress','mobile-ppg','vehicle-detection'][index]
 lines=project_descriptions[slug] if slug=='rfid-access' else research_descriptions[slug]
 image_url='/assets/publications/'+slug+'.jpg' if slug in ['damage-assessment','hepatitis-c','nightmare-prediction','ppg-stress'] else thumb(screen or cert)
 image_full=image_url if slug in ['damage-assessment','hepatitis-c','nightmare-prediction','ppg-stress'] else asset(screen or cert)
 publisher='Springer' if 'Springer' in venue else 'IEEE'
 image_label=publisher+' publication page: '+title if screen or slug in ['damage-assessment','hepatitis-c','nightmare-prediction','ppg-stress'] else 'Presentation certificate: '+title
 chevron='<svg class="entry-chevron" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="m6 9 6 6 6-6"/></svg>'
 certificate=f'<div class="publication-supporting-link">{doclink(cert,"View presentation certificate")}</div>' if cert else ''
 route='/publications/' if index<4 else '/publications/page-2/'
 search.append({'title':title,'url':route+'#'+slug,'text':' '.join(lines)+' '+authors+' '+venue+' '+year})
 return f'<article class="project-row publication-row" id="{slug}"><a class="project-visual" href="{image_full}" target="_blank" rel="noopener" aria-label="Open image: {esc(title)}"><img src="{image_url}" alt="{esc(image_label)}" width="240" height="240" loading="lazy"></a><div class="publication-content"><details class="entry-details"><summary><h2><span>{esc(title)}</span>{chevron}</h2></summary><div class="entry-body">{description_paragraph(lines)}<p class="publication-authors">{esc(authors)}</p><p class="publication-venue">{esc(venue)} · {year} · {kind}</p>{certificate}</div></details><a class="publication-button" href="{esc(url)}" target="_blank" rel="noopener" aria-label="View publication: {esc(title)}">View publication</a></div></article>'
page('/publications/','Publications',heading('PAPERS & SCHOLARLY WORK','Publications')+pubnav('Published')+'<div class="project-list publication-list">'+''.join(pubrow(p) for p in pubs[:4])+'</div><nav class="pagination" aria-label="Published paper pages"><span>1–4 of 7 papers</span><span aria-current="page">01</span><a href="/publications/page-2/">02 →</a></nav>')
page('/publications/page-2/','Published papers — page 2',heading('PAPERS & SCHOLARLY WORK','Publications')+pubnav('Published')+'<div class="project-list publication-list">'+''.join(pubrow(p) for p in pubs[4:])+'</div><nav class="pagination" aria-label="Published paper pages"><span>5–7 of 7 papers</span><a href="/publications/">← 01</a><span aria-current="page">02</span></nav>','Publications')
review=[('The Limits of Physics-Informed Digital Twins Under Hardware-Constrained Sampling: An HIL Study for Micro-Mechatronics','Md. Basim Al Zabir Shammo, Md. Anwar Hossain, et al.','Journal of Intelligent Manufacturing','3rd revision submitted'),('Vision-Based Crack Detection and Coverage Planning for Autonomous Mobile Robots','Md. Basim Al Zabir Shammo, Tarun Debnath, et al.','International Journal of Intelligent Robotics and Applications','1st revision ongoing'),('EthosVLA: Constitutional Safety for Embodied Vision-Language Agents','Noor Islam S. Mohammad, Md. Basim Al Zabir Shammo, et al.','ICLR 2027','Submitted'),('SIFT: Robust Meta-Faithfulness Verification of Chain-of-Thought Reasoning Under Distribution Shift','Noor Islam S. Mohammad, Md. Basim Al Zabir Shammo, et al.','ICLR 2027','Submitted'),('The Symmetry Budget: How Much Group Structure Should a Network Architecture Assume?','Noor Islam S. Mohammad, …, Md. Basim Al Zabir Shammo, et al.','NeurIPS 2026 Workshop','Submitted'),('Neural Representations for Universal Speech Restoration via Corruption-Conditioned Diffusion Models','Noor Islam S. Mohammad, …, Md. Basim Al Zabir Shammo','NeurIPS 2026 Workshop','Submitted')]
page('/publications/under-review/','Manuscripts under review',heading('WORK IN PROGRESS','Manuscripts under review','Submission and revision status as listed in my September 2026 CV.')+pubnav('Under review')+'<div class="compact-list">'+''.join(f'<details><summary><span><strong>{t}</strong><small>{v} · {s}</small></span><svg class="entry-chevron" viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="m6 9 6 6 6-6"/></svg></summary><p>{a}</p><p class="status-label">{s} · Not yet published</p></details>' for t,a,v,s in review)+'</div>','Publications')
page('/publications/presentations/','Conference presentations',heading('CONFERENCES','Presentations & contributions')+pubnav('Presentations')+'<div class="certificate-grid">'+''.join(f'<article><a class="certificate-image" href="{asset(f)}" target="_blank" rel="noopener"><img src="{thumb(f)}" alt="{esc(t)} certificate" loading="lazy"></a><p class="eyebrow">{meta}</p><h2>{t}</h2>{doclink(f)}</article>' for t,meta,f in [('Hepatitis C detection using ensemble boosting','BIM · 2025','461.pdf'),('Prediction of nightmares in children','COMPAS · 2025','COMPAS-2025.pdf'),('Stress detection using PPG signals','QPAIN · 2025','PID-1435.pdf'),('Predicting fear-related nightmares in children','IEEE CS BDC Summer Symposium · 2025','42.png')])+'</div>'+('<p class="bottom-link"><a class="text-link" href="/experience/bim-conference/">BIM conference photo ↗</a></p>' if 'BIM_Conference.jpeg' in files else ''),'Publications')

courses=[('Basic Robotic Behaviors and Odometry','University of Colorado Boulder','14 Sep 2025','Coursera WE0LC9FQ1LZM.pdf','https://coursera.org/verify/WE0LC9FQ1LZM'),('Machine Learning Specialization','Stanford Online & DeepLearning.AI','21 Dec 2024','Coursera PZ9E5UZY30JZ.pdf','https://coursera.org/verify/specialization/PZ9E5UZY30JZ'),('Programming Foundations with JavaScript, HTML and CSS','Duke University','20 Dec 2024','Coursera MRR37EXMPI0L.pdf','https://coursera.org/verify/MRR37EXMPI0L'),('SQL (Basic)','HackerRank','23 May 2024','canvas.png',None),('Python','Kaggle','13 Apr 2023','Basim Al Zabir - Python.png',None),('Unconscious Bias in Medicine','Stanford Medicine','25 Jan 2023','1674671819259.jpeg',None),('Introduction to Artificial Intelligence (AI)','IBM','23 Mar 2020','Coursera HJVFQX7U4K8B.pdf','https://coursera.org/verify/HJVFQX7U4K8B')]
page('/courses/','Courses',heading('CONTINUING LEARNING','Courses & certificates')+'<div class="certificate-grid course-certificates">'+''.join(f'<article><a class="certificate-image" href="{asset(f)}" target="_blank" rel="noopener"><img src="{thumb(f)}" alt="{esc(title)} certificate" loading="lazy"></a><p class="eyebrow">{org} · {date}</p><h2>{title}</h2><div class="resource-links">{doclink(f)}{ext(url,"Verify credential") if url else ""}</div></article>' for title,org,date,f,url in courses)+'</div>')
skill_groups=[
 ('Programming & modeling', [('Python','python-original.svg'),('R','r-original.svg'),('MATLAB','matlab-original.svg')]),
 ('Machine learning & computer vision', [('Scikit-learn','scikitlearn-original.svg'),('TensorFlow','tensorflow-original.svg'),('PyTorch','pytorch-original.svg'),('Keras','keras-original.svg'),('OpenCV','opencv-original.svg')]),
 ('Electronics & simulation', [('Arduino','arduino-original.svg'),('OpenModelica','https://raw.githubusercontent.com/OpenModelica/OpenModelica/master/doc/images/logo-editable.svg'),('Proteus','proteus.svg')]),
 ('Documentation & presentation', [('Microsoft Excel','microsoft-excel.png'),('Microsoft Word','microsoft-word.png'),('Microsoft PowerPoint','microsoft-powerpoint.png'),('LaTeX','latex-original.svg')])
]
def skill_row(title,items):
 return '<section class="skills-category"><h2>'+esc(title)+'</h2><div class="skill-logos">'+''.join('<figure class="skill-logo"><img src="'+(esc(icon) if icon.startswith('https://') else '/assets/skills/'+esc(icon))+'" alt="'+esc(label)+' logo" loading="lazy" width="130" height="96"><figcaption>'+esc(label)+'</figcaption></figure>' for label,icon in items)+'</div></section>'
page('/skills/','Skills',heading('TOOLS & METHODS','Skills')+'<div class="skills-gallery">'+''.join(skill_row(title,items) for title,items in skill_groups)+'</div>')

experience=heading('RESEARCH & ACADEMIC SERVICE','Experience')+'''<section class="split-row"><p class="date">JAN 2025 — JUL 2026</p><div><h2>Research Assistant</h2><p class="subtitle">Pabna University of Science and Technology</p><ul><li>Modeled dynamic loads for edge-deployed digital twins.</li><li>Developed sensor-fusion health indices and thermal forecasting methods.</li><li>Co-authored six papers on machine-learning diagnostic models.</li><li>Integrated computer vision and coverage planning in Webots.</li><li>Drafted robotics grant proposals and AI laboratory equipment specifications.</li></ul></div></section><section class="split-row"><p class="eyebrow">ACADEMIC SERVICE · 2025</p><div><h2>Peer reviewer</h2>'''+f'<p>28th International Conference on Computer and Information Technology (ICCIT)</p>{doclink("Reviewer_Md_Basim_Al_Zabir_Shammo.pdf")}<p>4th IEEE International Conference on Robotics, Automation, Artificial-Intelligence and Internet-of-Things (RAAICON)</p>{doclink("Dr. Md. Basim Al Zabir Shammo.pdf")}</div></section>'
if 'transcom.jpeg' in files:
 experience+='''<h2 class="section-title">Beyond the laboratory</h2><div class="small-cards"><a href="/experience/transcom/"><span class="eyebrow">INDUSTRY</span><h3>Transcom visit ↗</h3></a><a href="/experience/emk/"><span class="eyebrow">SCIENCE</span><h3>Physics at EMK ↗</h3></a><a href="/experience/bim-conference/"><span class="eyebrow">CONFERENCE</span><h3>BIM 2025 ↗</h3></a></div>'''
 page('/experience/transcom/','Transcom visit','<a class="back-link" href="/experience/">← Experience</a>'+heading('INDUSTRY','Transcom visit')+gallery(['transcom2.jpeg','transcom.jpeg','transcom3.jpeg'],['At the Transcom facility.','Industrial process equipment.','Inspection equipment on the production line.']),'Experience')
 page('/experience/emk/','Physics at EMK','<a class="back-link" href="/experience/">← Experience</a>'+heading('SCIENCE & LEARNING','Physics at EMK','The Observer Problem in Physics · George Musser · April 2024')+gallery(['physics_Emk.jpeg','physics_Emk2.jpeg'],['Discussion on the observer problem in physics.','Physics presentation at EMK.']),'Experience')
 page('/experience/bim-conference/','BIM 2025','<a class="back-link" href="/experience/">← Experience</a>'+heading('CONFERENCE · 25–27 SEP 2025','BIM 2025','3rd International Conference on Big Data, IoT and Machine Learning · Dhaka International University')+gallery(['BIM_Conference.jpeg'],['Basim at BIM 2025.'])+f'<p class="bottom-link">{doclink("461.pdf","View presentation certificate")}</p>','Experience')
experience+='<h2 class="section-title">Robotics demonstration</h2><p>Sharing a mobile robot prototype with students.</p><a class="text-link" href="/experience/robotics-demonstration/">View demonstration photo ↗</a>'
page('/experience/robotics-demonstration/','Robotics demonstration','<a class="back-link" href="/experience/">← Experience</a>'+heading('SCIENCE & ROBOTICS','Robotics demonstration')+gallery(['photo_6172214870665794036_y.jpg'],['Demonstrating a mobile robot prototype to students.'])+'<p class="bottom-link"><a class="text-link" href="/projects/">View Arduino and robot projects ↗</a></p>','Experience')
page('/experience/','Experience',experience)
achievements=heading('HONORS & RECOGNITION','Achievements')+'''<div class="honors"><section><span class="index">01</span><div><h2>PUST Conference and Travel Grant</h2><p>Grant recipient · Pabna University of Science and Technology</p></div></section><section><span class="index">02</span><div><h2>World Robotics Olympiad Bangladesh</h2><p>Finalist · 2025</p></div></section><section><span class="index">03</span><div><h2>Earth Champions Program Fellowship</h2><p>2022 cohort · Bangladesh Youth Environmental Initiative</p><p>Fully funded fellowship · BDT 100,000</p>'''+('<a class="text-link" href="/achievements/earth-champions/">Photos & press coverage ↗</a>' if 'ecp2022.jpeg' in files else '')+'''</div></section><section><span class="index">04</span><div><h2>Rajuk Intra Talent Hunt</h2><p>1st position · Science Project · 2018</p>'''+doclink('1611727701619.jpeg','View award')+'</div></section></div>'
page('/achievements/','Achievements',achievements)
if 'ecp2022.jpeg' in files:
 page('/achievements/earth-champions/','Earth Champions Program','<a class="back-link" href="/achievements/">← Achievements</a>'+heading('FELLOWSHIP · 2022 COHORT','Earth Champions Program','Environmental stewardship with Bangladesh Youth Environmental Initiative. Earth Camp took place in January 2023.')+'''<div class="feature-gallery" data-gallery><div class="gallery-stage"><img id="gallery-image" src="'''+thumb('Ecp2022_me.jpeg')+'''" alt="Basim speaking at Earth Camp"><div class="gallery-caption"><span id="gallery-caption">Basim speaking at Earth Camp</span><div><button class="icon-button" data-previous aria-label="Previous photo">←</button><span id="gallery-count">1 / 5</span><button class="icon-button" data-next aria-label="Next photo">→</button></div></div></div><div class="gallery-thumbs">'''+''.join(f'<button data-src="{thumb(n)}" data-caption="{esc(c)}" aria-label="Show photo {i+1}: {esc(c)}" aria-pressed="{str(i==0).lower()}"><img src="{thumb(n)}" alt="" loading="lazy"></button>' for i,(n,c) in enumerate([('Ecp2022_me.jpeg','Basim speaking at Earth Camp'),('ecp2022.jpeg','Earth Champions Program participants'),('ecp_2022.jpeg','Environmental stewardship at Earth Camp'),('ecp2022_team.jpeg','Team discussion during the program'),('ecp2022_2.jpeg','Field activities with fellow participants')]))+'</div></div><h2 class="section-title">Press coverage</h2><p>The Earth Camp was featured in Daily Bangla on 24 January 2023.</p>'+gallery(['Ecp news paper.jpeg','Screenshot from 2026-09-23 16-41-55.png'],['Daily Bangla print feature: The Story of the Earth Camp.','Screenshot of the Daily Bangla online feature.']),'Achievements')
(out/'search-index.json').write_text(json.dumps(search))
print(f'Created {len(search)} pages and organized {len(files)} uploads.')

from prepare_github_pages import prepare_export
prepare_export(out)
